# Generated by Django 5.0.2 on 2024-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_DB',
            fields=[
                ('bookno', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=10)),
                ('authorname', models.CharField(max_length=10)),
                ('yearofpublishing', models.DateField()),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
